config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: "welcome#index"
  get('/leaderboard', { to: 'welcome#leaderboard'})

  resources :quizzes do
    post :submit, on: :member
    resources :questions do
      resources :answers, shallow: true
    end
    resources :takes, only: [ :create, :update, :destroy ]
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizMasters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to "Home", root_path %> </a>
            </li>

            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to "Quizzes", quizzes_path %></a>
            </li>
            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to "Leaderboard", leaderboard_path %></a>
            </li>
        
            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to "New Quiz", new_quiz_path %></a>
            </li>
        
          </ul>
          <ul class="navbar-nav mr-2">
          <% if user_signed_in? %>
            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to current_user.first_name, edit_user_registration_path %> </a>

            </li>
            <li class="nav-item pull-right mr-2">
              <a class="nav-link" href="#"> <%= link_to "Sign Out", destroy_user_session_path, method: :delete %> </a>
            </li>
       
          <% else %>
            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to "Sign In", new_user_session_path %></a>
            </li>
            <li class="nav-item mr-2">
              <a class="nav-link" href="#"><%= link_to "Sign Up", new_user_registration_path %></a>
            </li>
          <%end%>
          </ul>
        </div>
      </nav>
    </header>

    <% flash.each do |type, message| %>
      <% if type == "notice" && message == "You will receive an email with instructions on how to reset your password in a few minutes." %>
        <div class="alert alert-warning %> alert-dismissible fade show m-2" role="alert">
      <% elsif type == "notice" %>
        <div class="alert alert-success %> alert-dismissible fade show m-2" role="alert">
      <% else %>
        <div class="alert alert-<%= type %> alert-dismissible fade show m-2" role="alert">
      <% end %>
          <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

    